/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.40
 * Generated at: 2025-04-09 17:54:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>Barbería B&L</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"./css-1/style1.css\">\r\n");
      out.write("        <script src=\"https://kit.fontawesome.com/a076d05399.js\"></script>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <header style=\"display: flex; flex-direction: row;\">\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <img src=\"./assets/logo.png\" alt=\"Barberia B&L Logo\">\r\n");
      out.write("                <h1 style=\"font-size: 35px !important;\">Barberia B&L</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <nav>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li ><a href=\"#\">Inicio</a></li>\r\n");
      out.write("                    <li ><a href=\"./Frame-login-general/Frame-login-generaal.jsp\">Servicios</a></li>\r\n");
      out.write("                    <li ><a href=\"./Frame-login-general/Frame-login-generaal.jsp\">Productos</a></li>\r\n");
      out.write("                    <li ><a href=\"./Frame-login-general/Frame-login-generaal.jsp\">Sedes</a></li>\r\n");
      out.write("                    <li ><a href=\"./Frame-login-general/Frame-login-generaal.jsp\">Reservas</a></li>\r\n");
      out.write("                    <li >\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <div style=\"display: flex; flex-direction: row;\" class=\"user-icon\">\r\n");
      out.write("                <a href=\"./Frame-login-general/Frame-login-generaal.jsp\"><h5>Iniciar Sesión</h5></a>\r\n");
      out.write("                <img src=\"./assets/user-icon.png\" alt=\"User Icon\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("        <main>\r\n");
      out.write("\r\n");
      out.write("            <div style=\"width: 100%; display: flex; flex-direction: row;\">\r\n");
      out.write("                <div style=\"width: 35%; align-items: center;\">\r\n");
      out.write("                    <div class=\"col-md-12\" id=\"left_section_index_1\">\r\n");
      out.write("                        <div id=\"carouselExampleIndicators\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("                            <div class=\"carousel-inner\">\r\n");
      out.write("                                <div class=\"carousel-item active\">\r\n");
      out.write("                                    <img src=\"./assets/imagen menu1.png\" class=\"d-block w-100\" alt=\"Imagen 1\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"carousel-item\">\r\n");
      out.write("                                    <img src=\"./assets/imagen menu2.png\" class=\"d-block w-100\" alt=\"Imagen 2\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"carousel-item\">\r\n");
      out.write("                                    <img src=\"./assets/imagen menu3.png\" class=\"d-block w-100\" alt=\"Imagen 3\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a class=\"carousel-control-prev\" href=\"#carouselExampleIndicators\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("                                <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                <span class=\"sr-only\">Previous</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a class=\"carousel-control-next\" href=\"#carouselExampleIndicators\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("                                <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                <span class=\"sr-only\">Next</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div style=\"width: 65%; align-items: center; padding: 40px;\">\r\n");
      out.write("                    <div class=\"content\" id=\"content_index_1\">\r\n");
      out.write("                        <h2 class=\"title\">En Barbería B&L</h2>\r\n");
      out.write("                        <p  style=\"text-align: justify\" class=\"large-text\">\r\n");
      out.write("                            En Barbería B&L, entendemos que un buen corte de cabello es mucho más que solo una cuestión de apariencia; \r\n");
      out.write("                            es una experiencia que refleja tu estilo y personalidad. Desde nuestra apertura, nos hemos dedicado a brindar \r\n");
      out.write("                            un servicio de calidad excepcional, combinando técnicas tradicionales con las últimas tendencias en moda masculina. \r\n");
      out.write("                            Nuestro equipo está compuesto por barberos altamente capacitados que se apasionan por su arte y se esfuerzan \r\n");
      out.write("                            por superar las expectativas de cada cliente que cruza nuestra puerta.\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <p style=\"text-align: justify\"  class=\"large-text\">\r\n");
      out.write("                            Además, nos comprometemos a usar solo productos de la más alta calidad, cuidadosamente seleccionados para \r\n");
      out.write("                            cuidar de tu cabello y piel. Ya sea que busques un estilo clásico o algo más moderno y atrevido, nuestro equipo \r\n");
      out.write("                            está aquí para ayudarte a encontrar el look perfecto para ti.\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div style=\"display:flex; flex-direction: row; align-items: center; justify-content: space-around; width: 100%; background-color: #f2f2f2; padding: 40px; border-radius: 15px;\">\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"servicio-item\" style=\"width: 40%\">\r\n");
      out.write("                            <h4>Corte de Cabello</h4>\r\n");
      out.write("                            <div id=\"carruselCorteCabello\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("                                <div class=\"carousel-inner\">\r\n");
      out.write("                                    <div class=\"carousel-item active\">\r\n");
      out.write("                                        <img src=\"./assets/CorteDeCabello1.png\" class=\"d-block w-100\" alt=\"Corte de Cabello 1\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"carousel-item\">\r\n");
      out.write("                                        <img src=\"./assets/CorteDeCabello2.png\" class=\"d-block w-100\" alt=\"Corte de Cabello 2\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"carousel-item\">\r\n");
      out.write("                                        <img src=\"./assets/CorteDeCabello3.png\" class=\"d-block w-100\" alt=\"Corte de Cabello 3\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <a class=\"carousel-control-prev\" href=\"#carruselCorteCabello\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("                                    <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                    <span class=\"sr-only\">Anterior</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a class=\"carousel-control-next\" href=\"#carruselCorteCabello\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("                                    <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                    <span class=\"sr-only\">Siguiente</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"servicio-item\" style=\"width: 40%\">\r\n");
      out.write("                            <h4>Afeitado Clásico</h4>\r\n");
      out.write("                            <div id=\"carruselAfeitadoClasico\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("                                <div class=\"carousel-inner\">\r\n");
      out.write("                                    <div class=\"carousel-item active\">\r\n");
      out.write("                                        <img src=\"./assets/AfeitadoClasico1.png\" class=\"d-block w-100\" alt=\"Afeitado Clásico 1\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"carousel-item\">\r\n");
      out.write("                                        <img src=\"./assets/AfeitadoClasico2.png\" class=\"d-block w-100\" alt=\"Afeitado Clásico 2\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"carousel-item\">\r\n");
      out.write("                                        <img src=\"./assets/AfeitadoClasico3.png\" class=\"d-block w-100\" alt=\"Afeitado Clásico 3\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <a class=\"carousel-control-prev\" href=\"#carruselAfeitadoClasico\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("                                    <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                    <span class=\"sr-only\">Anterior</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a class=\"carousel-control-next\" href=\"#carruselAfeitadoClasico\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("                                    <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                                    <span class=\"sr-only\">Siguiente</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>          \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div style=\"width: 100%; display: flex; flex-direction: row; background-color: #f2f2f2; margin-top: 30px;  margin-bottom: 30px; border-radius:15px;\">\r\n");
      out.write("                <div style=\"width: 35%; align-items: center; justify-items: center; margin: auto;\">\r\n");
      out.write("                    <h1>Nuestros</h1>\r\n");
      out.write("                    <h1>Productos</h1>\r\n");
      out.write("                    <h1>OwO</h1>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div style=\"width: 65%; align-items: center; padding: 20px;\">\r\n");
      out.write("                    <div style=\"width: 100%; display: flex; flex-direction: row;\" >\r\n");
      out.write("                        <div class=\"producto-box\">\r\n");
      out.write("                            <img src=\"./assets/servicios-producto1.png\" alt=\"Producto 1\">\r\n");
      out.write("                            <p>NOMBRE DEL PRODUCTO 1</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"producto-box\">\r\n");
      out.write("                            <img src=\"./assets/servicios-producto2.png\" alt=\"Producto 2\">\r\n");
      out.write("                            <p>NOMBRE DEL PRODUCTO 2</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"producto-box\">\r\n");
      out.write("                            <img src=\"./assets/servicios-producto3.png\" alt=\"Producto 3\">\r\n");
      out.write("                            <p>NOMBRE DEL PRODUCTO 3</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"producto-box\">\r\n");
      out.write("                            <img src=\"./assets/servicios-producto4.png\" alt=\"Producto 4\">\r\n");
      out.write("                            <p>NOMBRE DEL PRODUCTO 4</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"producto-box\">\r\n");
      out.write("                            <img src=\"./assets/servicios-producto5.png\" alt=\"Producto 5\">\r\n");
      out.write("                            <p>NOMBRE DEL PRODUCTO 5</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div> \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <footer>\r\n");
      out.write("            <div class=\"footer-content\">\r\n");
      out.write("                <div class=\"footer-left\">\r\n");
      out.write("                    <p>Contacto: +51 997 259 085 / +51 950 758 586</p>\r\n");
      out.write("                    <p>Dirección: Cdr 3. Calle Teselia, San Carlos, San Juan de Lurigancho</p>\r\n");
      out.write("                    <p>Teléfono: (123) 456-7890</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-right\">\r\n");
      out.write("                    <p>Cancelaciones con 24 horas de anticipación.</p>\r\n");
      out.write("                    <p>Reembolsos no disponibles.</p>\r\n");
      out.write("                    <p>Diseño web: \"Los Terreneitor de San Carlos\"</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"copyright\">\r\n");
      out.write("                <p>© 2024 Barbería B&L. Todos los derechos reservados.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.7/dist/umd/popper.min.js\"></script>\r\n");
      out.write("        <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
