/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.40
 * Generated at: 2025-04-10 17:49:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Administrador.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Users.BoletasDAO;
import Users.Boletas;
import java.util.LinkedList;

public final class boletas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("Users.Boletas");
    _jspx_imports_classes.add("Users.BoletasDAO");
    _jspx_imports_classes.add("java.util.LinkedList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    // Obtener la lista de boletas
    BoletasDAO boletasDAO = new BoletasDAO();
    LinkedList<Boletas> boletas = boletasDAO.list();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Gestión de Boletas - Barbería BYL</title>\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Font Awesome for icons -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --primary-color: #3498db;\r\n");
      out.write("            --secondary-color: #2ecc71;\r\n");
      out.write("            --light-bg: #f4f6f7;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: var(--light-bg);\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar {\r\n");
      out.write("            background-color: #2c3e50;\r\n");
      out.write("            color: white;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            transition: all 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar .nav-link {\r\n");
      out.write("            color: rgba(255,255,255,0.7);\r\n");
      out.write("            transition: all 0.3s;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar .nav-link:hover {\r\n");
      out.write("            background-color: rgba(255,255,255,0.1);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar img {\r\n");
      out.write("            max-width: 30px;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .main-content {\r\n");
      out.write("            margin-left: 250px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            background-color: var(--light-bg);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-form, .table-empleados {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 4px 6px rgba(0,0,0,0.1);\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-form {\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .table-empleados thead {\r\n");
      out.write("            background-color: var(--primary-color);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-action {\r\n");
      out.write("            margin: 0 5px;\r\n");
      out.write("        }\r\n");
      out.write("        /* Estilos para el estado de las boletas */\r\n");
      out.write(".status-pagado {\r\n");
      out.write("    background-color: #28a745;  /* Verde para \"Pagado\" */\r\n");
      out.write("    color: white;  /* Texto blanco */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".status-pendiente {\r\n");
      out.write("    background-color: #ffc107;  /* Amarillo para \"Pendiente\" */\r\n");
      out.write("    color: black;  /* Texto negro */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".status-anulado {\r\n");
      out.write("    background-color: #dc3545;  /* Rojo para \"Anulado\" */\r\n");
      out.write("    color: white;  /* Texto blanco */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .sidebar {\r\n");
      out.write("                width: 80px;\r\n");
      out.write("            }\r\n");
      out.write("            .main-content {\r\n");
      out.write("                margin-left: 80px;\r\n");
      out.write("            }\r\n");
      out.write("            .sidebar .nav-link span {\r\n");
      out.write("                display: none;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("             <!-- Sidebar -->\r\n");
      out.write("            <div class=\"col-md-2 sidebar\">\r\n");
      out.write("                <div class=\"logo text-center my-4\">\r\n");
      out.write("                    <img src=\"../../Administrador/img/barber-logo.jpg\" alt=\"Logo\" class=\"img-fluid rounded-circle\" style=\"width: 80px;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"nav flex-column\">\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"../../Administrador/pages/citas.jsp\" class=\"nav-link\">\r\n");
      out.write("                            <i class=\"fas fa-calendar\"></i> <span>Citas</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"../../Usuario/pages/usuarios.jsp\" class=\"nav-link\">\r\n");
      out.write("                            <i class=\"fas fa-users\"></i> <span>Usuarios</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"../../Administrador/pages/proveedor.jsp\" class=\"nav-link\">\r\n");
      out.write("                            <i class=\"fas fa-store\"></i> <span>Proveedores</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"../../Administrador/pages/servicio.jsp\" class=\"nav-link\">\r\n");
      out.write("                            <i class=\"fas fa-concierge-bell\"></i> <span>Servicios</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"../../Administrador/pages/productos.jsp\" class=\"nav-link active\">\r\n");
      out.write("                            <i class=\"fas fa-box\"></i> <span>Productos</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"../../Administrador/pages/empleado.jsp\" class=\"nav-link\">\r\n");
      out.write("                            <i class=\"fas fa-users-cog\"></i> <span>Empleados</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"../../Administrador/pages/boletas.jsp\" class=\"nav-link\">\r\n");
      out.write("                            <i class=\"fas fa-receipt\"></i> <span>Boletas</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item mt-5\">\r\n");
      out.write("                        <a href=\"../../Frame-login-general/Frame-login-generaal.jsp\" class=\"nav-link\">\r\n");
      out.write("                            <i class=\"fas fa-sign-out-alt\"></i> <span>Salir</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-10 main-content\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <h1 class=\"mb-4\">\r\n");
      out.write("                            <i class=\"fas fa-receipt me-2\"></i>Gestión de Boletas\r\n");
      out.write("                        </h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-4\">\r\n");
      out.write("    <a href=\"reportedepersonasconmascompras.jsp\" class=\"btn btn-secondary\">\r\n");
      out.write("        <i class=\"fas fa-file-pdf\"></i> Ver Reporte de Servicios\r\n");
      out.write("    </a>\r\n");
      out.write("</div>\r\n");
      out.write("                <!-- Mensaje de error si existe -->\r\n");
      out.write("                ");
 
                    String errorMensaje = (String) request.getAttribute("errorMensaje");
                    if (errorMensaje != null && !errorMensaje.isEmpty()) { 
                
      out.write("\r\n");
      out.write("                    <div class=\"alert alert-danger alert-dismissible fade show\" role=\"alert\">\r\n");
      out.write("                        <i class=\"fas fa-exclamation-triangle me-2\"></i>\r\n");
      out.write("                        ");
      out.print( errorMensaje );
      out.write("\r\n");
      out.write("                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- Formulario para crear boleta -->\r\n");
      out.write("                <div class=\"card-form\">\r\n");
      out.write("                    <h2>\r\n");
      out.write("                        <i class=\"fas fa-file-invoice-dollar me-2\"></i>Crear Nueva Boleta\r\n");
      out.write("                    </h2>\r\n");
      out.write("                    <form action=\"/Proyecto-Barberia-BYL/BoletasServlet\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"accion\" value=\"crear\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                <label class=\"form-label\">\r\n");
      out.write("                                    <i class=\"fas fa-user me-2\"></i>Cliente\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <input type=\"text\" name=\"cliente\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                <label class=\"form-label\">\r\n");
      out.write("                                    <i class=\"fas fa-calendar me-2\"></i>Fecha\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <input type=\"date\" name=\"fecha\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                <label class=\"form-label\">\r\n");
      out.write("                                    <i class=\"fas fa-money-bill-wave me-2\"></i>Total Bruto\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <input type=\"number\" name=\"totalBruto\" step=\"0.01\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                <label class=\"form-label\">\r\n");
      out.write("                                    <i class=\"fas fa-credit-card me-2\"></i>Método de Pago\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <select name=\"metodoPago\" class=\"form-select\" required>\r\n");
      out.write("                                    <option value=\"\">Seleccionar Método de Pago</option>\r\n");
      out.write("                                    <option value=\"Efectivo\">Efectivo</option>\r\n");
      out.write("                                    <option value=\"Tarjeta\">Tarjeta</option>\r\n");
      out.write("                                    <option value=\"Transferencia\">Transferencia</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-12 mb-3\">\r\n");
      out.write("                                <label class=\"form-label\">\r\n");
      out.write("                                    <i class=\"fas fa-check-circle me-2\"></i>Estado\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <select name=\"estado\" class=\"form-select\" required>\r\n");
      out.write("                                    <option value=\"\">Seleccionar Estado</option>\r\n");
      out.write("                                    <option value=\"Pendiente\">Pendiente</option>\r\n");
      out.write("                                    <option value=\"Pagado\">Pagado</option>\r\n");
      out.write("                                    <option value=\"Anulado\">Anulado</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-end\">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-custom\">\r\n");
      out.write("                                <i class=\"fas fa-plus me-2\"></i>Crear Boleta\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Tabla de Boletas -->\r\n");
      out.write("                <div class=\"table-responsive\">\r\n");
      out.write("                    <table class=\"table table-hover mb-0\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>ID</th>\r\n");
      out.write("                                <th>Cliente</th>\r\n");
      out.write("                                <th>Fecha</th>\r\n");
      out.write("                                <th>Total Bruto</th>\r\n");
      out.write("                                <th>IGV</th>\r\n");
      out.write("                                <th>Total Neto</th>\r\n");
      out.write("                                <th>Método de Pago</th>\r\n");
      out.write("                                <th>Estado</th>\r\n");
      out.write("                                <th>Acciones</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            ");
 for (Boletas boleta : boletas) { 
      out.write("\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>");
      out.print( boleta.getIdBoleta() );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( boleta.getCliente() );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( boleta.getFecha() );
      out.write("</td>\r\n");
      out.write("                                    <td>S/ ");
      out.print( boleta.getTotalBruto() );
      out.write("</td>\r\n");
      out.write("                                    <td>S/ ");
      out.print( boleta.getIgv() );
      out.write("</td>\r\n");
      out.write("                                    <td>S/ ");
      out.print( boleta.getTotalNeto() );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( boleta.getMetodoPago() );
      out.write("</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <span class=\"badge status-badge \r\n");
      out.write("                                            ");
      out.print( boleta.getEstado().equals("Pagado") ? "status-pagado" : 
                                                boleta.getEstado().equals("Pendiente") ? "status-pendiente" : 
                                                "status-anulado" );
      out.write("\">\r\n");
      out.write("                                            ");
      out.print( boleta.getEstado() );
      out.write("\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <div class=\"btn-group\" role=\"group\">\r\n");
      out.write("                                            <button type=\"button\" class=\"btn btn-sm btn-outline-primary\" \r\n");
      out.write("                                                    data-bs-toggle=\"modal\" \r\n");
      out.write("                                                    data-bs-target=\"#editModal");
      out.print( boleta.getIdBoleta() );
      out.write("\">\r\n");
      out.write("                                                <i class=\"fas fa-edit\"></i>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                            <button type=\"button\" class=\"btn btn-sm btn-outline-danger\" \r\n");
      out.write("                                                    data-bs-toggle=\"modal\" \r\n");
      out.write("                                                    data-bs-target=\"#deleteModal");
      out.print( boleta.getIdBoleta() );
      out.write("\">\r\n");
      out.write("                                                <i class=\"fas fa-trash\"></i>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("\r\n");
      out.write("                               <!-- Modal de Edición -->\r\n");
      out.write("<div class=\"modal fade\" id=\"editModal");
      out.print( boleta.getIdBoleta() );
      out.write("\" tabindex=\"-1\" aria-labelledby=\"editModalLabel");
      out.print( boleta.getIdBoleta() );
      out.write("\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\" id=\"editModalLabel");
      out.print( boleta.getIdBoleta() );
      out.write("\">Editar Boleta</h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <form action=\"/Proyecto-Barberia-BYL/BoletasServlet\" method=\"post\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"accion\" value=\"editar\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"idBoleta\" value=\"");
      out.print( boleta.getIdBoleta() );
      out.write("\">\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label class=\"form-label\">Cliente</label>\r\n");
      out.write("                        <input type=\"text\" name=\"cliente\" class=\"form-control\" value=\"");
      out.print( boleta.getCliente() );
      out.write("\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label class=\"form-label\">Fecha</label>\r\n");
      out.write("                        <input type=\"date\" name=\"fecha\" class=\"form-control\" value=\"");
      out.print( boleta.getFecha() );
      out.write("\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label class=\"form-label\">Total Bruto</label>\r\n");
      out.write("                        <input type=\"number\" name=\"totalBruto\" class=\"form-control\" value=\"");
      out.print( boleta.getTotalBruto() );
      out.write("\" step=\"0.01\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label class=\"form-label\">Método de Pago</label>\r\n");
      out.write("                        <select name=\"metodoPago\" class=\"form-select\" required>\r\n");
      out.write("                            <option value=\"\">Seleccionar Método de Pago</option>\r\n");
      out.write("                            <option value=\"Efectivo\" ");
      out.print( boleta.getMetodoPago().equals("Efectivo") ? "selected" : "" );
      out.write(">Efectivo</option>\r\n");
      out.write("                            <option value=\"Tarjeta\" ");
      out.print( boleta.getMetodoPago().equals("Tarjeta") ? "selected" : "" );
      out.write(">Tarjeta</option>\r\n");
      out.write("                            <option value=\"Transferencia\" ");
      out.print( boleta.getMetodoPago().equals("Transferencia") ? "selected" : "" );
      out.write(">Transferencia</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label class=\"form-label\">Estado</label>\r\n");
      out.write("                        <select name=\"estado\" class=\"form-select\" required>\r\n");
      out.write("                            <option value=\"\">Seleccionar Estado</option>\r\n");
      out.write("                            <option value=\"Pendiente\" ");
      out.print( boleta.getEstado().equals("Pendiente") ? "selected" : "" );
      out.write(">Pendiente</option>\r\n");
      out.write("                            <option value=\"Pagado\" ");
      out.print( boleta.getEstado().equals("Pagado") ? "selected" : "" );
      out.write(">Pagado</option>\r\n");
      out.write("                            <option value=\"Anulado\" ");
      out.print( boleta.getEstado().equals("Anulado") ? "selected" : "" );
      out.write(">Anulado</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"text-end\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\">Actualizar Boleta</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <!-- Modal de Eliminación -->\r\n");
      out.write("<div class=\"modal fade\" id=\"deleteModal");
      out.print( boleta.getIdBoleta() );
      out.write("\" tabindex=\"-1\" aria-labelledby=\"deleteModalLabel");
      out.print( boleta.getIdBoleta() );
      out.write("\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\" id=\"deleteModalLabel");
      out.print( boleta.getIdBoleta() );
      out.write("\">Eliminar Boleta</h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <p>¿Estás seguro de que deseas eliminar esta boleta?</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <form action=\"/Proyecto-Barberia-BYL/BoletasServlet\" method=\"post\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"accion\" value=\"eliminar\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"idBoleta\" value=\"");
      out.print( boleta.getIdBoleta() );
      out.write("\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancelar</button>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-danger\">Eliminar</button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap JS y Popper.js -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
