/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.40
 * Generated at: 2025-04-09 20:50:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Administrador.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Users.CitaDAO;
import Users.Cita;
import java.util.LinkedList;

public final class citas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("Users.CitaDAO");
    _jspx_imports_classes.add("Users.Cita");
    _jspx_imports_classes.add("java.util.LinkedList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    // Obtener la lista de citas
    CitaDAO citaDAO = new CitaDAO();
    LinkedList<Cita> citas = citaDAO.list();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Gestión de Citas</title>\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Font Awesome for icons -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --primary-color: #3498db;\r\n");
      out.write("            --secondary-color: #2ecc71;\r\n");
      out.write("            --light-bg: #f4f6f7;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: var(--light-bg);\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar {\r\n");
      out.write("            background-color: #2c3e50;\r\n");
      out.write("            color: white;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            transition: all 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar .nav-link {\r\n");
      out.write("            color: rgba(255,255,255,0.7);\r\n");
      out.write("            transition: all 0.3s;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar .nav-link:hover {\r\n");
      out.write("            background-color: rgba(255,255,255,0.1);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar img {\r\n");
      out.write("            max-width: 30px;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .main-content {\r\n");
      out.write("            margin-left: 250px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            background-color: var(--light-bg);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-form, .table-empleados {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 4px 6px rgba(0,0,0,0.1);\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-form {\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .table-empleados thead {\r\n");
      out.write("            background-color: var(--primary-color);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-action {\r\n");
      out.write("            margin: 0 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .sidebar {\r\n");
      out.write("                width: 80px;\r\n");
      out.write("            }\r\n");
      out.write("            .main-content {\r\n");
      out.write("                margin-left: 80px;\r\n");
      out.write("            }\r\n");
      out.write("            .sidebar .nav-link span {\r\n");
      out.write("                display: none;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("             <!-- Sidebar -->\r\n");
      out.write("            <div class=\"col-md-2 sidebar\">\r\n");
      out.write("                <div class=\"logo text-center my-4\">\r\n");
      out.write("                    <img src=\"../../Administrador/img/barber-logo.jpg\" alt=\"Logo\" class=\"img-fluid rounded-circle\" style=\"width: 80px;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"nav flex-column\">\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"../../Administrador/pages/citas.jsp\" class=\"nav-link\">\r\n");
      out.write("                            <i class=\"fas fa-calendar\"></i> <span>Citas</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"../../Usuario/pages/usuarios.jsp\" class=\"nav-link\">\r\n");
      out.write("                            <i class=\"fas fa-users\"></i> <span>Usuarios</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"../../Administrador/pages/proveedor.jsp\" class=\"nav-link\">\r\n");
      out.write("                            <i class=\"fas fa-store\"></i> <span>Proveedores</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"../../Administrador/pages/servicio.jsp\" class=\"nav-link\">\r\n");
      out.write("                            <i class=\"fas fa-concierge-bell\"></i> <span>Servicios</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"../../Administrador/pages/productos.jsp\" class=\"nav-link active\">\r\n");
      out.write("                            <i class=\"fas fa-box\"></i> <span>Productos</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"../../Administrador/pages/empleado.jsp\" class=\"nav-link\">\r\n");
      out.write("                            <i class=\"fas fa-users-cog\"></i> <span>Empleados</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"../../Administrador/pages/boletas.jsp\" class=\"nav-link\">\r\n");
      out.write("                            <i class=\"fas fa-receipt\"></i> <span>Boletas</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item mt-5\">\r\n");
      out.write("                        <a href=\"../../Frame-login-general/Frame-login-generaal.jsp\" class=\"nav-link\">\r\n");
      out.write("                            <i class=\"fas fa-sign-out-alt\"></i> <span>Salir</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Main Content -->\r\n");
      out.write("            <div class=\"col-md-10 main-content\">\r\n");
      out.write("                <h1 class=\"my-4\">Gestión de Citas</h1>\r\n");
      out.write("\r\n");
      out.write("                <!-- Formulario para crear cita -->\r\n");
      out.write("                <div class=\"card-form\">\r\n");
      out.write("                    <h2 class=\"mb-4\">Crear Cita</h2>\r\n");
      out.write("                    <form action=\"/Proyecto-Barberia-BYL/CitaServlet\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"accion\" value=\"crear\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                <label class=\"form-label\">Empleado</label>\r\n");
      out.write("                                <input type=\"text\" name=\"empleado\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                <label class=\"form-label\">Servicio</label>\r\n");
      out.write("                                <input type=\"text\" name=\"servicio\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                <label class=\"form-label\">Sede</label>\r\n");
      out.write("                                <input type=\"text\" name=\"sede\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                <label class=\"form-label\">Fecha</label>\r\n");
      out.write("                                <input type=\"date\" name=\"fecha\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                <label class=\"form-label\">Hora Inicio</label>\r\n");
      out.write("                                <input type=\"time\" name=\"horaInicio\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                <label class=\"form-label\">Hora Fin</label>\r\n");
      out.write("                                <input type=\"time\" name=\"horaFin\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                <label class=\"form-label\">Nombre del Cliente</label>\r\n");
      out.write("                                <input type=\"text\" name=\"clienteNombre\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                <label class=\"form-label\">Estado</label>\r\n");
      out.write("                                <select name=\"estado\" class=\"form-control\" required>\r\n");
      out.write("                                    <option value=\"PENDIENTE\">Pendiente</option>\r\n");
      out.write("                                    <option value=\"VALIDADO\">Validado</option>\r\n");
      out.write("                                    <option value=\"CANCELADO\">Cancelado</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("                            <i class=\"fas fa-plus\"></i> Crear Cita\r\n");
      out.write("                        </button>\r\n");
      out.write("                        \r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Botón para reporte de servicios -->\r\n");
      out.write("<div class=\"mb-4\">\r\n");
      out.write("    <button class=\"btn btn-secondary\" onclick=\"abrirReporteServicios()\">Ver Reporte de Servicios</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    function abrirReporteServicios() {\r\n");
      out.write("        // Cambia la ruta al servlet que genera el reporte de servicios\r\n");
      out.write("        window.open('/Proyecto-Barberia-BYL/GenerarReporteServiciosPDF', '_blank');\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("                <!-- Tabla de citas -->\r\n");
      out.write("                <div class=\"card table-responsive\">\r\n");
      out.write("                    <div class=\"card-header bg-primary text-white\">\r\n");
      out.write("                        <h2 class=\"mb-0\">Lista de Citas</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <table class=\"table table-striped table-hover mb-0\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>ID</th>\r\n");
      out.write("                                <th>Empleado</th>\r\n");
      out.write("                                <th>Servicio</th>\r\n");
      out.write("                                <th>Sede</th>\r\n");
      out.write("                                <th>Fecha</th>\r\n");
      out.write("                                <th>Hora Inicio</th>\r\n");
      out.write("                                <th>Hora Fin</th>\r\n");
      out.write("                                <th>Cliente</th>\r\n");
      out.write("                                <th>Estado</th>\r\n");
      out.write("                                <th>Acciones</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            ");
 for(Cita cita : citas) { 
      out.write("\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>");
      out.print( cita.getIdCita() );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( cita.getEmpleado() );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( cita.getServicio() );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( cita.getSede() );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( cita.getFecha() );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( cita.getHoraInicio() );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( cita.getHoraFin() );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( cita.getClienteNombre() );
      out.write("</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        ");
 
                                            String estadoClass = "";
                                            switch(cita.getEstado()) {
                                                case "PENDIENTE": 
                                                    estadoClass = "badge bg-warning"; 
                                                    break;
                                                case "VALIDADO": 
                                                    estadoClass = "badge bg-success"; 
                                                    break;
                                                case "CANCELADO": 
                                                    estadoClass = "badge bg-danger"; 
                                                    break;
                                            }
                                        
      out.write("\r\n");
      out.write("                                        <span class=\"");
      out.print( estadoClass );
      out.write('"');
      out.write('>');
      out.print( cita.getEstado() );
      out.write("</span>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <!-- Botones de acciones -->\r\n");
      out.write("                                        <div class=\"btn-group\" role=\"group\">\r\n");
      out.write("                                            <button class=\"btn btn-sm btn-info edit-btn\" data-id=\"");
      out.print( cita.getIdCita() );
      out.write("\" data-bs-toggle=\"modal\" data-bs-target=\"#editModal\">\r\n");
      out.write("                                                <i class=\"fas fa-edit\"></i>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                            <button class=\"btn btn-sm btn-danger delete-btn\" data-id=\"");
      out.print( cita.getIdCita() );
      out.write("\" data-bs-toggle=\"modal\" data-bs-target=\"#deleteModal\">\r\n");
      out.write("                                                <i class=\"fas fa-trash\"></i>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Modals for Edit and Delete -->\r\n");
      out.write("                <!-- Edit Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"editModal\" tabindex=\"-1\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\">Editar Cita</h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <!-- Formulario de edición -->\r\n");
      out.write("                <form action=\"/Proyecto-Barberia-BYL/CitaServlet\" method=\"post\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"accion\" value=\"actualizar\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"idCita\" id=\"editIdCita\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                            <label class=\"form-label\">Empleado</label>\r\n");
      out.write("                            <input type=\"text\" name=\"empleado\" id=\"editEmpleado\" class=\"form-control\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                            <label class=\"form-label\">Servicio</label>\r\n");
      out.write("                            <input type=\"text\" name=\"servicio\" id=\"editServicio\" class=\"form-control\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                            <label class=\"form-label\">Sede</label>\r\n");
      out.write("                            <input type=\"text\" name=\"sede\" id=\"editSede\" class=\"form-control\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                            <label class=\"form-label\">Fecha</label>\r\n");
      out.write("                            <input type=\"date\" name=\"fecha\" id=\"editFecha\" class=\"form-control\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                            <label class=\"form-label\">Hora Inicio</label>\r\n");
      out.write("                            <input type=\"time\" name=\"horaInicio\" id=\"editHoraInicio\" class=\"form-control\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                            <label class=\"form-label\">Hora Fin</label>\r\n");
      out.write("                            <input type=\"time\" name=\"horaFin\" id=\"editHoraFin\" class=\"form-control\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                            <label class=\"form-label\">Nombre del Cliente</label>\r\n");
      out.write("                            <input type=\"text\" name=\"clienteNombre\" id=\"editClienteNombre\" class=\"form-control\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                            <label class=\"form-label\">Estado</label>\r\n");
      out.write("                            <select name=\"estado\" id=\"editEstado\" class=\"form-control\" required>\r\n");
      out.write("                                <option value=\"PENDIENTE\">Pendiente</option>\r\n");
      out.write("                                <option value=\"VALIDADO\">Validado</option>\r\n");
      out.write("                                <option value=\"CANCELADO\">Cancelado</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("                        <i class=\"fas fa-save\"></i> Guardar Cambios\r\n");
      out.write("                    </button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- Delete Modal -->\r\n");
      out.write("                <div class=\"modal fade\" id=\"deleteModal\" tabindex=\"-1\">\r\n");
      out.write("                    <div class=\"modal-dialog\">\r\n");
      out.write("                        <div class=\"modal-content\">\r\n");
      out.write("                            <div class=\"modal-header\">\r\n");
      out.write("                                <h5 class=\"modal-title\">Confirmar Eliminación</h5>\r\n");
      out.write("                                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"modal-body\">\r\n");
      out.write("                                <p>¿Está seguro de que desea eliminar esta cita?</p>\r\n");
      out.write("                                <form action=\"/Proyecto-Barberia-BYL/CitaServlet\" method=\"post\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"accion\" value=\"eliminar\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"idCita\" id=\"deleteIdCita\">\r\n");
      out.write("                                    <div class=\"modal-footer\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancelar</button>\r\n");
      out.write("                                        <button type=\"submit\" class=\"btn btn-danger\">Eliminar</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Script para abrir reporte -->\r\n");
      out.write("    <script>\r\n");
      out.write("        function abrirReporte() {\r\n");
      out.write("            window.open('reportedeventas.jsp', 'Reporte de Ventas', 'width=800,height=600');\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("    <!-- Bootstrap JS and dependencies -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("              // Edit modal handling\r\n");
      out.write("    const editButtons = document.querySelectorAll('.edit-btn');\r\n");
      out.write("    const editModal = document.getElementById('editModal');\r\n");
      out.write("    \r\n");
      out.write("    // Campos del formulario de edición\r\n");
      out.write("    const editIdCitaInput = document.getElementById('editIdCita');\r\n");
      out.write("    const editEmpleadoInput = document.getElementById('editEmpleado');\r\n");
      out.write("    const editServicioInput = document.getElementById('editServicio');\r\n");
      out.write("    const editSedeInput = document.getElementById('editSede');\r\n");
      out.write("    const editFechaInput = document.getElementById('editFecha');\r\n");
      out.write("    const editHoraInicioInput = document.getElementById('editHoraInicio');\r\n");
      out.write("    const editHoraFinInput = document.getElementById('editHoraFin');\r\n");
      out.write("    const editClienteNombreInput = document.getElementById('editClienteNombre');\r\n");
      out.write("    const editEstadoInput = document.getElementById('editEstado');\r\n");
      out.write("\r\n");
      out.write("    editButtons.forEach(button => {\r\n");
      out.write("        button.addEventListener('click', function() {\r\n");
      out.write("            const citaId = this.getAttribute('data-id');\r\n");
      out.write("            const empleado = this.getAttribute('data-empleado');\r\n");
      out.write("            const servicio = this.getAttribute('data-servicio');\r\n");
      out.write("            const sede = this.getAttribute('data-sede');\r\n");
      out.write("            const fecha = this.getAttribute('data-fecha');\r\n");
      out.write("            const horaInicio = this.getAttribute('data-horaInicio');\r\n");
      out.write("            const horaFin = this.getAttribute('data-horaFin');\r\n");
      out.write("            const clienteNombre = this.getAttribute('data-clienteNombre');\r\n");
      out.write("            const estado = this.getAttribute('data-estado');\r\n");
      out.write("\r\n");
      out.write("            // Llenar los campos con los datos de la cita seleccionada\r\n");
      out.write("            editIdCitaInput.value = citaId;\r\n");
      out.write("            editEmpleadoInput.value = empleado;\r\n");
      out.write("            editServicioInput.value = servicio;\r\n");
      out.write("            editSedeInput.value = sede;\r\n");
      out.write("            editFechaInput.value = fecha;\r\n");
      out.write("            editHoraInicioInput.value = horaInicio;\r\n");
      out.write("            editHoraFinInput.value = horaFin;\r\n");
      out.write("            editClienteNombreInput.value = clienteNombre;\r\n");
      out.write("            editEstadoInput.value = estado;\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("            // Delete modal handling\r\n");
      out.write("            const deleteButtons = document.querySelectorAll('.delete-btn');\r\n");
      out.write("            const deleteModal = document.getElementById('deleteModal');\r\n");
      out.write("            const deleteIdCitaInput = document.getElementById('deleteIdCita');\r\n");
      out.write("\r\n");
      out.write("            deleteButtons.forEach(button => {\r\n");
      out.write("                button.addEventListener('click', function() {\r\n");
      out.write("                    const citaId = this.getAttribute('data-id');\r\n");
      out.write("                    deleteIdCitaInput.value = citaId;\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
