/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.40
 * Generated at: 2025-04-10 17:13:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Administrador.pages;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Users.ServicioDAO;
import Users.Servicio;
import java.util.LinkedList;

public final class servicio_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("Users.ServicioDAO");
    _jspx_imports_classes.add("Users.Servicio");
    _jspx_imports_classes.add("java.util.LinkedList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    // Obtenemos la lista de servicios desde el DAO
    ServicioDAO servicioDAO = new ServicioDAO();
    LinkedList<Servicio> servicios = servicioDAO.list();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Gestión de Servicios</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --primary-color: #3498db;\r\n");
      out.write("            --secondary-color: #2ecc71;\r\n");
      out.write("            --light-bg: #f4f6f7;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: var(--light-bg);\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar {\r\n");
      out.write("            background-color: #2c3e50;\r\n");
      out.write("            color: white;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            transition: all 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar .nav-link {\r\n");
      out.write("            color: rgba(255,255,255,0.7);\r\n");
      out.write("            transition: all 0.3s;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar .nav-link:hover {\r\n");
      out.write("            background-color: rgba(255,255,255,0.1);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar img {\r\n");
      out.write("            max-width: 30px;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .main-content {\r\n");
      out.write("            margin-left: 250px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            background-color: var(--light-bg);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-form, .table-services {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 4px 6px rgba(0,0,0,0.1);\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-form {\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .table-services thead {\r\n");
      out.write("            background-color: var(--primary-color);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-action {\r\n");
      out.write("            margin: 0 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .sidebar {\r\n");
      out.write("                width: 80px;\r\n");
      out.write("            }\r\n");
      out.write("            .main-content {\r\n");
      out.write("                margin-left: 80px;\r\n");
      out.write("            }\r\n");
      out.write("            .sidebar .nav-link span {\r\n");
      out.write("                display: none;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <!-- Sidebar -->\r\n");
      out.write("            <div class=\"col-md-2 sidebar\">\r\n");
      out.write("                <div class=\"logo text-center my-4\">\r\n");
      out.write("                    <img src=\"../../Administrador/img/barber-logo.jpg\" alt=\"Logo\" class=\"img-fluid rounded-circle\" style=\"width: 80px;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"nav flex-column\">\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"../../Administrador/pages/citas.jsp\" class=\"nav-link\">\r\n");
      out.write("                            <i class=\"fas fa-calendar\"></i> <span>Citas</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"../../Usuario/pages/usuarios.jsp\" class=\"nav-link\">\r\n");
      out.write("                            <i class=\"fas fa-users\"></i> <span>Usuarios</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"../../Administrador/pages/proveedor.jsp\" class=\"nav-link\">\r\n");
      out.write("                            <i class=\"fas fa-store\"></i> <span>Proveedores</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"../../Administrador/pages/servicio.jsp\" class=\"nav-link active\">\r\n");
      out.write("                            <i class=\"fas fa-concierge-bell\"></i> <span>Servicios</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"../../Administrador/pages/productos.jsp\" class=\"nav-link\">\r\n");
      out.write("                            <i class=\"fas fa-box\"></i> <span>Productos</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"../../Administrador/pages/empleado.jsp\" class=\"nav-link\">\r\n");
      out.write("                            <i class=\"fas fa-users-cog\"></i> <span>Empleados</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a href=\"../../Administrador/pages/boletas.jsp\" class=\"nav-link\">\r\n");
      out.write("                            <i class=\"fas fa-receipt\"></i> <span>Boletas</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item mt-5\">\r\n");
      out.write("                        <a href=\"../../Frame-login-general/Frame-login-generaal.jsp\" class=\"nav-link\">\r\n");
      out.write("                            <i class=\"fas fa-sign-out-alt\"></i> <span>Salir</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Main Content -->\r\n");
      out.write("            <div class=\"col-md-10 main-content\">\r\n");
      out.write("                <h1 class=\"my-4\">Gestión de Servicios</h1>\r\n");
      out.write("<!-- Botón para reporte de servicios -->\r\n");
      out.write("<div class=\"mb-4\">\r\n");
      out.write("    <a href=\"reportedeserviciosmassolicitados.jsp\" class=\"btn btn-secondary\">\r\n");
      out.write("        <i class=\"fas fa-file-pdf\"></i> Ver Reporte de Servicios\r\n");
      out.write("    </a>\r\n");
      out.write("</div>\r\n");
      out.write("                <!-- Formulario para crear servicio -->\r\n");
      out.write("                <div class=\"card-form\">\r\n");
      out.write("                    <h2 class=\"mb-4\">Crear Servicio</h2>\r\n");
      out.write("                    <form action=\"/Proyecto-Barberia-BYL/ServicioServlet\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"accion\" value=\"crear\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                <label class=\"form-label\">Nombre del Servicio</label>\r\n");
      out.write("                                <input type=\"text\" name=\"nombreservicio\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                <label class=\"form-label\">Descripción</label>\r\n");
      out.write("                                <input type=\"text\" name=\"descripcion\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                <label class=\"form-label\">Precio</label>\r\n");
      out.write("                                <input type=\"number\" step=\"0.01\" name=\"precio\" class=\"form-control\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("                            <i class=\"fas fa-plus\"></i> Crear Servicio\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Tabla de servicios -->\r\n");
      out.write("                <div class=\"card table-responsive\">\r\n");
      out.write("                    <div class=\"card-header bg-primary text-white\">\r\n");
      out.write("                        <h2 class=\"mb-0\">Lista de Servicios</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <table class=\"table table-striped table-hover mb-0\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>ID</th>\r\n");
      out.write("                                <th>Nombre</th>\r\n");
      out.write("                                <th>Descripción</th>\r\n");
      out.write("                                <th>Precio</th>\r\n");
      out.write("                                <th>Acciones</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            ");
 for (Servicio servicio : servicios) { 
      out.write("\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>");
      out.print( servicio.getIdServicio() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print( servicio.getNombreservicio() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print( servicio.getDescripcion() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print( servicio.getPrecio() );
      out.write("</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"btn-group\" role=\"group\">\r\n");
      out.write("                                        <!-- Editar Servicio -->\r\n");
      out.write("                                        <button type=\"button\" class=\"btn btn-warning btn-action\" data-bs-toggle=\"modal\" data-bs-target=\"#editModal");
      out.print( servicio.getIdServicio() );
      out.write("\">\r\n");
      out.write("                                            <i class=\"fas fa-edit\"></i>\r\n");
      out.write("                                        </button>\r\n");
      out.write("\r\n");
      out.write("                                        <!-- Eliminar Servicio -->\r\n");
      out.write("                                        <form action=\"/Proyecto-Barberia-BYL/ServicioServlet\" method=\"post\" class=\"d-inline\">\r\n");
      out.write("                                            <input type=\"hidden\" name=\"accion\" value=\"eliminar\">\r\n");
      out.write("                                            <input type=\"hidden\" name=\"id\" value=\"");
      out.print( servicio.getIdServicio() );
      out.write("\">\r\n");
      out.write("                                            <button type=\"submit\" class=\"btn btn-danger btn-action\" onclick=\"return confirm('¿Estás seguro de eliminar este servicio?');\">\r\n");
      out.write("                                                <i class=\"fas fa-trash\"></i>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- Modal para Editar Servicio -->\r\n");
      out.write("                            <div class=\"modal fade\" id=\"editModal");
      out.print( servicio.getIdServicio() );
      out.write("\" tabindex=\"-1\" aria-labelledby=\"editModalLabel");
      out.print( servicio.getIdServicio() );
      out.write("\" aria-hidden=\"true\">\r\n");
      out.write("                                <div class=\"modal-dialog\">\r\n");
      out.write("                                    <div class=\"modal-content\">\r\n");
      out.write("                                        <div class=\"modal-header\">\r\n");
      out.write("                                            <h5 class=\"modal-title\" id=\"editModalLabel");
      out.print( servicio.getIdServicio() );
      out.write("\">Editar Servicio</h5>\r\n");
      out.write("                                            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <form action=\"/Proyecto-Barberia-BYL/ServicioServlet\" method=\"post\">\r\n");
      out.write("                                            <div class=\"modal-body\">\r\n");
      out.write("                                                <input type=\"hidden\" name=\"accion\" value=\"actualizar\">\r\n");
      out.write("                                                <input type=\"hidden\" name=\"id\" value=\"");
      out.print( servicio.getIdServicio() );
      out.write("\">\r\n");
      out.write("                                                <div class=\"mb-3\">\r\n");
      out.write("                                                    <label class=\"form-label\">Nombre del Servicio</label>\r\n");
      out.write("                                                    <input type=\"text\" name=\"nombreservicio\" class=\"form-control\" value=\"");
      out.print( servicio.getNombreservicio() );
      out.write("\" required>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"mb-3\">\r\n");
      out.write("                                                    <label class=\"form-label\">Descripción</label>\r\n");
      out.write("                                                    <input type=\"text\" name=\"descripcion\" class=\"form-control\" value=\"");
      out.print( servicio.getDescripcion() );
      out.write("\" required>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"mb-3\">\r\n");
      out.write("                                                    <label class=\"form-label\">Precio</label>\r\n");
      out.write("                                                    <input type=\"number\" step=\"0.01\" name=\"precio\" class=\"form-control\" value=\"");
      out.print( servicio.getPrecio() );
      out.write("\" required>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"modal-footer\">\r\n");
      out.write("                                                <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancelar</button>\r\n");
      out.write("                                                <button type=\"submit\" class=\"btn btn-primary\">Guardar Cambios</button>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
